customhost = "awsproject.c6q8p0purapb.ap-south-1.rds.amazonaws.com"
customuser = "intellipaat"
custompass = "intellipaat123"
customdb = "employee"
custombucket = "employeeproject"
customregion = "ap-south-1"
